# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_FLQuant_FLQuant_multiplier_assignment_operator <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuant_multiplier_assignment_operator`, flq1, flq2)
}

test_FLQuantAD_FLQuant_multiplier_assignment_operator <- function(flqad1, flq2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuant_multiplier_assignment_operator`, flqad1, flq2)
}

test_FLQuantAD_FLQuantAD_multiplier_assignment_operator <- function(flqad1, flqad2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuantAD_multiplier_assignment_operator`, flqad1, flqad2)
}

test_FLQuant_double_multiplier_assignment_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_double_multiplier_assignment_operator`, flq1, value)
}

test_FLQuantAD_double_multiplier_assignment_operator <- function(flqad1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_double_multiplier_assignment_operator`, flqad1, value)
}

test_FLQuantAD_adouble_multiplier_assignment_operator <- function(flqad1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_adouble_multiplier_assignment_operator`, flqad1, value)
}

test_FLQuant_FLQuant_multiplier_operator <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuant_multiplier_operator`, flq1, flq2)
}

test_FLQuantAD_FLQuant_multiplier_operator <- function(flqad1, flq2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuant_multiplier_operator`, flqad1, flq2)
}

test_FLQuant_FLQuantAD_multiplier_operator <- function(flq1, flqad2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuantAD_multiplier_operator`, flq1, flqad2)
}

test_FLQuantAD_FLQuantAD_multiplier_operator <- function(flqad1, flqad2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuantAD_multiplier_operator`, flqad1, flqad2)
}

test_FLQuant_double_multiplier_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_double_multiplier_operator`, flq1, value)
}

test_double_FLQuant_multiplier_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_double_FLQuant_multiplier_operator`, value, flq1)
}

test_double_FLQuantAD_multiplier_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_double_FLQuantAD_multiplier_operator`, value, flq1)
}

test_FLQuantAD_double_multiplier_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_double_multiplier_operator`, flq1, value)
}

test_FLQuant_adouble_multiplier_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_adouble_multiplier_operator`, flq1, value)
}

test_adouble_FLQuant_multiplier_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_adouble_FLQuant_multiplier_operator`, value, flq1)
}

test_FLQuantAD_adouble_multiplier_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_adouble_multiplier_operator`, flq1, value)
}

test_adouble_FLQuantAD_multiplier_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_adouble_FLQuantAD_multiplier_operator`, value, flq1)
}

test_FLQuant_FLQuant_division_assignment_operator <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuant_division_assignment_operator`, flq1, flq2)
}

test_FLQuantAD_FLQuant_division_assignment_operator <- function(flqad1, flq2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuant_division_assignment_operator`, flqad1, flq2)
}

test_FLQuantAD_FLQuantAD_division_assignment_operator <- function(flqad1, flqad2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuantAD_division_assignment_operator`, flqad1, flqad2)
}

test_FLQuant_double_division_assignment_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_double_division_assignment_operator`, flq1, value)
}

test_FLQuantAD_double_division_assignment_operator <- function(flqad1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_double_division_assignment_operator`, flqad1, value)
}

test_FLQuantAD_adouble_division_assignment_operator <- function(flqad1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_adouble_division_assignment_operator`, flqad1, value)
}

test_FLQuant_FLQuant_division_operator <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuant_division_operator`, flq1, flq2)
}

test_FLQuantAD_FLQuant_division_operator <- function(flqad1, flq2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuant_division_operator`, flqad1, flq2)
}

test_FLQuant_FLQuantAD_division_operator <- function(flq1, flqad2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuantAD_division_operator`, flq1, flqad2)
}

test_FLQuantAD_FLQuantAD_division_operator <- function(flqad1, flqad2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuantAD_division_operator`, flqad1, flqad2)
}

test_FLQuant_double_division_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_double_division_operator`, flq1, value)
}

test_double_FLQuant_division_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_double_FLQuant_division_operator`, value, flq1)
}

test_double_FLQuantAD_division_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_double_FLQuantAD_division_operator`, value, flq1)
}

test_FLQuantAD_double_division_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_double_division_operator`, flq1, value)
}

test_FLQuant_adouble_division_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_adouble_division_operator`, flq1, value)
}

test_adouble_FLQuant_division_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_adouble_FLQuant_division_operator`, value, flq1)
}

test_FLQuantAD_adouble_division_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_adouble_division_operator`, flq1, value)
}

test_adouble_FLQuantAD_division_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_adouble_FLQuantAD_division_operator`, value, flq1)
}

test_FLQuant_FLQuant_subtraction_assignment_operator <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuant_subtraction_assignment_operator`, flq1, flq2)
}

test_FLQuantAD_FLQuant_subtraction_assignment_operator <- function(flqad1, flq2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuant_subtraction_assignment_operator`, flqad1, flq2)
}

test_FLQuantAD_FLQuantAD_subtraction_assignment_operator <- function(flqad1, flqad2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuantAD_subtraction_assignment_operator`, flqad1, flqad2)
}

test_FLQuant_double_subtraction_assignment_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_double_subtraction_assignment_operator`, flq1, value)
}

test_FLQuantAD_double_subtraction_assignment_operator <- function(flqad1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_double_subtraction_assignment_operator`, flqad1, value)
}

test_FLQuantAD_adouble_subtraction_assignment_operator <- function(flqad1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_adouble_subtraction_assignment_operator`, flqad1, value)
}

test_FLQuant_FLQuant_subtraction_operator <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuant_subtraction_operator`, flq1, flq2)
}

test_FLQuantAD_FLQuant_subtraction_operator <- function(flqad1, flq2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuant_subtraction_operator`, flqad1, flq2)
}

test_FLQuant_FLQuantAD_subtraction_operator <- function(flq1, flqad2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuantAD_subtraction_operator`, flq1, flqad2)
}

test_FLQuantAD_FLQuantAD_subtraction_operator <- function(flqad1, flqad2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuantAD_subtraction_operator`, flqad1, flqad2)
}

test_FLQuant_double_subtraction_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_double_subtraction_operator`, flq1, value)
}

test_double_FLQuant_subtraction_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_double_FLQuant_subtraction_operator`, value, flq1)
}

test_double_FLQuantAD_subtraction_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_double_FLQuantAD_subtraction_operator`, value, flq1)
}

test_FLQuantAD_double_subtraction_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_double_subtraction_operator`, flq1, value)
}

test_FLQuant_adouble_subtraction_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_adouble_subtraction_operator`, flq1, value)
}

test_adouble_FLQuant_subtraction_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_adouble_FLQuant_subtraction_operator`, value, flq1)
}

test_FLQuantAD_adouble_subtraction_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_adouble_subtraction_operator`, flq1, value)
}

test_adouble_FLQuantAD_subtraction_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_adouble_FLQuantAD_subtraction_operator`, value, flq1)
}

test_FLQuant_FLQuant_addition_assignment_operator <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuant_addition_assignment_operator`, flq1, flq2)
}

test_FLQuantAD_FLQuant_addition_assignment_operator <- function(flqad1, flq2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuant_addition_assignment_operator`, flqad1, flq2)
}

test_FLQuantAD_FLQuantAD_addition_assignment_operator <- function(flqad1, flqad2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuantAD_addition_assignment_operator`, flqad1, flqad2)
}

test_FLQuant_double_addition_assignment_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_double_addition_assignment_operator`, flq1, value)
}

test_FLQuantAD_double_addition_assignment_operator <- function(flqad1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_double_addition_assignment_operator`, flqad1, value)
}

test_FLQuantAD_adouble_addition_assignment_operator <- function(flqad1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_adouble_addition_assignment_operator`, flqad1, value)
}

test_FLQuant_FLQuant_addition_operator <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuant_addition_operator`, flq1, flq2)
}

test_FLQuantAD_FLQuant_addition_operator <- function(flqad1, flq2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuant_addition_operator`, flqad1, flq2)
}

test_FLQuant_FLQuantAD_addition_operator <- function(flq1, flqad2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuantAD_addition_operator`, flq1, flqad2)
}

test_FLQuantAD_FLQuantAD_addition_operator <- function(flqad1, flqad2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuantAD_addition_operator`, flqad1, flqad2)
}

test_FLQuant_double_addition_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_double_addition_operator`, flq1, value)
}

test_double_FLQuant_addition_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_double_FLQuant_addition_operator`, value, flq1)
}

test_double_FLQuantAD_addition_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_double_FLQuantAD_addition_operator`, value, flq1)
}

test_FLQuantAD_double_addition_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_double_addition_operator`, flq1, value)
}

test_FLQuant_adouble_addition_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuant_adouble_addition_operator`, flq1, value)
}

test_adouble_FLQuant_addition_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_adouble_FLQuant_addition_operator`, value, flq1)
}

test_FLQuantAD_adouble_addition_operator <- function(flq1, value) {
    .Call(`_FLasherTests_test_FLQuantAD_adouble_addition_operator`, flq1, value)
}

test_adouble_FLQuantAD_addition_operator <- function(value, flq1) {
    .Call(`_FLasherTests_test_adouble_FLQuantAD_addition_operator`, value, flq1)
}

test_FLQuant_log <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_log`, flq)
}

test_FLQuantAD_log <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_log`, flq)
}

test_FLQuant_exp <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_exp`, flq)
}

test_FLQuantAD_exp <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_exp`, flq)
}

test_composite_arithmetic_operators <- function(flqad, flq, value) {
    .Call(`_FLasherTests_test_composite_arithmetic_operators`, flqad, flq, value)
}

test_FLQuant_quant_sum <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_quant_sum`, flq)
}

test_FLQuantAD_quant_sum <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_quant_sum`, flq)
}

test_FLQuant_quant_mean <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_quant_mean`, flq)
}

test_FLQuant_year_sum <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_year_sum`, flq)
}

test_FLQuant_year_mean <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_year_mean`, flq)
}

test_FLQuantAD_quant_mean <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_quant_mean`, flq)
}

test_FLQuant_max_quant <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_max_quant`, flq)
}

test_FLQuantAD_max_quant <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_max_quant`, flq)
}

test_FLQuant_scale_by_max_quant <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_scale_by_max_quant`, flq)
}

test_FLQuantAD_scale_by_max_quant <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_scale_by_max_quant`, flq)
}

test_FLQuantAD_unit_sum <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_unit_sum`, flq)
}

test_sweep_multADAD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_multADAD`, flq1, flq2)
}

test_sweep_multDD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_multDD`, flq1, flq2)
}

test_sweep_multADD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_multADD`, flq1, flq2)
}

test_sweep_multDAD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_multDAD`, flq1, flq2)
}

test_sweep_divADAD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_divADAD`, flq1, flq2)
}

test_sweep_divDD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_divDD`, flq1, flq2)
}

test_sweep_divADD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_divADD`, flq1, flq2)
}

test_sweep_divDAD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_divDAD`, flq1, flq2)
}

test_sweep_plusADAD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_plusADAD`, flq1, flq2)
}

test_sweep_plusDD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_plusDD`, flq1, flq2)
}

test_sweep_plusADD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_plusADD`, flq1, flq2)
}

test_sweep_plusDAD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_plusDAD`, flq1, flq2)
}

test_sweep_minusADAD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_minusADAD`, flq1, flq2)
}

test_sweep_minusDD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_minusDD`, flq1, flq2)
}

test_sweep_minusADD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_minusADD`, flq1, flq2)
}

test_sweep_minusDAD <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_sweep_minusDAD`, flq1, flq2)
}

test_int_is_na <- function(val) {
    .Call(`_FLasherTests_test_int_is_na`, val)
}

test_double_is_na <- function(val) {
    .Call(`_FLasherTests_test_double_is_na`, val)
}

test_simple_FLCatch_sexp_constructor <- function(flc_sexp) {
    .Call(`_FLasherTests_test_simple_FLCatch_sexp_constructor`, flc_sexp)
}

test_FLCatch_sexp_constructor <- function(flc_sexp) {
    .Call(`_FLasherTests_test_FLCatch_sexp_constructor`, flc_sexp)
}

test_FLCatchAD_sexp_constructor <- function(flc_sexp) {
    .Call(`_FLasherTests_test_FLCatchAD_sexp_constructor`, flc_sexp)
}

test_FLCatch_as_wrap <- function(flc) {
    .Call(`_FLasherTests_test_FLCatch_as_wrap`, flc)
}

test_FLCatchAD_as_wrap <- function(flc) {
    .Call(`_FLasherTests_test_FLCatchAD_as_wrap`, flc)
}

test_FLCatch_copy_constructor <- function(flc1) {
    .Call(`_FLasherTests_test_FLCatch_copy_constructor`, flc1)
}

test_FLCatchAD_copy_constructor <- function(flc1) {
    .Call(`_FLasherTests_test_FLCatchAD_copy_constructor`, flc1)
}

test_FLCatch_copy_constructor2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLCatch_copy_constructor2`, flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatchAD_copy_constructor2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLCatchAD_copy_constructor2`, flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatch_assignment_operator <- function(flc1) {
    .Call(`_FLasherTests_test_FLCatch_assignment_operator`, flc1)
}

test_FLCatchAD_assignment_operator <- function(flc1) {
    .Call(`_FLasherTests_test_FLCatchAD_assignment_operator`, flc1)
}

test_FLCatch_assignment_operator2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLCatch_assignment_operator2`, flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatchAD_assignment_operator2 <- function(flc1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLCatchAD_assignment_operator2`, flc1, quant, year, unit, season, area, iter, value)
}

test_FLCatch_const_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLCatch_const_get_accessors`, flc, quant, year, unit, season, area, iter)
}

test_FLCatch_const_get_accessors_subset <- function(flc, indices_min, indices_max) {
    .Call(`_FLasherTests_test_FLCatch_const_get_accessors_subset`, flc, indices_min, indices_max)
}

test_FLCatchAD_const_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLCatchAD_const_get_accessors`, flc, quant, year, unit, season, area, iter)
}

test_FLCatch_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLCatch_get_accessors`, flc, quant, year, unit, season, area, iter)
}

test_FLCatchAD_get_accessors <- function(flc, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLCatchAD_get_accessors`, flc, quant, year, unit, season, area, iter)
}

test_FLCatch_set_accessors <- function(flc, quant, year, unit, season, area, iter, values) {
    .Call(`_FLasherTests_test_FLCatch_set_accessors`, flc, quant, year, unit, season, area, iter, values)
}

test_FLCatchAD_set_accessors <- function(flc, quant, year, unit, season, area, iter, values) {
    .Call(`_FLasherTests_test_FLCatchAD_set_accessors`, flc, quant, year, unit, season, area, iter, values)
}

test_FLCatch_revenue_subset <- function(flc, indices_min, indices_max) {
    .Call(`_FLasherTests_test_FLCatch_revenue_subset`, flc, indices_min, indices_max)
}

test_FLCatch_revenue <- function(flc) {
    .Call(`_FLasherTests_test_FLCatch_revenue`, flc)
}

test_FLCatch_landings <- function(flc) {
    .Call(`_FLasherTests_test_FLCatch_landings`, flc)
}

test_FLCatchAD_landings <- function(flc) {
    .Call(`_FLasherTests_test_FLCatchAD_landings`, flc)
}

test_FLCatch_discards <- function(flc) {
    .Call(`_FLasherTests_test_FLCatch_discards`, flc)
}

test_FLCatchAD_discards <- function(flc) {
    .Call(`_FLasherTests_test_FLCatchAD_discards`, flc)
}

test_FLCatch_catch_n <- function(flc) {
    .Call(`_FLasherTests_test_FLCatch_catch_n`, flc)
}

test_FLCatchAD_catch_n <- function(flc) {
    .Call(`_FLasherTests_test_FLCatchAD_catch_n`, flc)
}

test_FLCatch_catch_wt <- function(flc) {
    .Call(`_FLasherTests_test_FLCatch_catch_wt`, flc)
}

test_FLCatchAD_catch_wt <- function(flc) {
    .Call(`_FLasherTests_test_FLCatchAD_catch_wt`, flc)
}

test_FLCatch_catches <- function(flc) {
    .Call(`_FLasherTests_test_FLCatch_catches`, flc)
}

test_FLCatchAD_catches <- function(flc) {
    .Call(`_FLasherTests_test_FLCatchAD_catches`, flc)
}

test_FLCatch_discards_ratio <- function(flc) {
    .Call(`_FLasherTests_test_FLCatch_discards_ratio`, flc)
}

test_FLCatchAD_discards_ratio <- function(flc) {
    .Call(`_FLasherTests_test_FLCatchAD_discards_ratio`, flc)
}

test_FLCatch_landings_sel <- function(flc) {
    .Call(`_FLasherTests_test_FLCatch_landings_sel`, flc)
}

test_FLCatchAD_landings_sel <- function(flc) {
    .Call(`_FLasherTests_test_FLCatchAD_landings_sel`, flc)
}

test_FLCatch_discards_sel <- function(flc) {
    .Call(`_FLasherTests_test_FLCatch_discards_sel`, flc)
}

test_FLCatchAD_discards_sel <- function(flc) {
    .Call(`_FLasherTests_test_FLCatchAD_discards_sel`, flc)
}

test_FLCatchAD_catch_q_params <- function(flc, indices) {
    .Call(`_FLasherTests_test_FLCatchAD_catch_q_params`, flc, indices)
}

test_FLCatchAD_catch_q_params_subset <- function(flc, indices_min, indices_max) {
    .Call(`_FLasherTests_test_FLCatchAD_catch_q_params_subset`, flc, indices_min, indices_max)
}

test_FLCatches_as_wrap <- function(flcs) {
    .Call(`_FLasherTests_test_FLCatches_as_wrap`, flcs)
}

test_FLCatches_sexp_constructor <- function(flcs_sexp1) {
    .Call(`_FLasherTests_test_FLCatches_sexp_constructor`, flcs_sexp1)
}

test_FLCatches_FLCatch_constructor <- function(flc) {
    .Call(`_FLasherTests_test_FLCatches_FLCatch_constructor`, flc)
}

test_FLCatches_copy_constructor <- function(flcs) {
    .Call(`_FLasherTests_test_FLCatches_copy_constructor`, flcs)
}

test_FLCatches_copy_constructor2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLCatches_copy_constructor2`, flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatches_assignment_operator <- function(flcs) {
    .Call(`_FLasherTests_test_FLCatches_assignment_operator`, flcs)
}

test_FLCatches_assignment_operator2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLCatches_assignment_operator2`, flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatches_function_operator <- function(flcs, flc) {
    .Call(`_FLasherTests_test_FLCatches_function_operator`, flcs, flc)
}

test_FLCatches_get_ncatches <- function(flc_sexp1) {
    .Call(`_FLasherTests_test_FLCatches_get_ncatches`, flc_sexp1)
}

test_FLCatches_const_get_single_index_accessor <- function(flcs, element) {
    .Call(`_FLasherTests_test_FLCatches_const_get_single_index_accessor`, flcs, element)
}

test_FLCatches_get_single_index_accessor <- function(flcs, element) {
    .Call(`_FLasherTests_test_FLCatches_get_single_index_accessor`, flcs, element)
}

test_FLCatches_const_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLCatches_const_get_value_accessor`, flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatches_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLCatches_get_value_accessor`, flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatches_set_single_index_accessor <- function(flcs, element, flc) {
    .Call(`_FLasherTests_test_FLCatches_set_single_index_accessor`, flcs, element, flc)
}

test_FLCatches_set_value_accessor <- function(flcs, element, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLCatches_set_value_accessor`, flcs, element, quant, year, unit, season, area, iter, value)
}

test_FLCatchesAD_as_wrap <- function(flcs) {
    .Call(`_FLasherTests_test_FLCatchesAD_as_wrap`, flcs)
}

test_FLCatchesAD_sexp_constructor <- function(flcs_sexp1) {
    .Call(`_FLasherTests_test_FLCatchesAD_sexp_constructor`, flcs_sexp1)
}

test_FLCatchesAD_FLCatchAD_constructor <- function(flc) {
    .Call(`_FLasherTests_test_FLCatchesAD_FLCatchAD_constructor`, flc)
}

test_FLCatchesAD_copy_constructor <- function(flcs) {
    .Call(`_FLasherTests_test_FLCatchesAD_copy_constructor`, flcs)
}

test_FLCatchesAD_copy_constructor2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLCatchesAD_copy_constructor2`, flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatchesAD_assignment_operator <- function(flcs) {
    .Call(`_FLasherTests_test_FLCatchesAD_assignment_operator`, flcs)
}

test_FLCatchesAD_assignment_operator2 <- function(flcs1, catches, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLCatchesAD_assignment_operator2`, flcs1, catches, quant, year, unit, season, area, iter, value)
}

test_FLCatchesAD_function_operator <- function(flcs, flc) {
    .Call(`_FLasherTests_test_FLCatchesAD_function_operator`, flcs, flc)
}

test_FLCatchesAD_get_ncatches <- function(flc_sexp1) {
    .Call(`_FLasherTests_test_FLCatchesAD_get_ncatches`, flc_sexp1)
}

test_FLCatchesAD_const_get_single_index_accessor <- function(flcs, element) {
    .Call(`_FLasherTests_test_FLCatchesAD_const_get_single_index_accessor`, flcs, element)
}

test_FLCatchesAD_get_single_index_accessor <- function(flcs, element) {
    .Call(`_FLasherTests_test_FLCatchesAD_get_single_index_accessor`, flcs, element)
}

test_FLCatchesAD_const_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLCatchesAD_const_get_value_accessor`, flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatchesAD_get_value_accessor <- function(flcs, catches, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLCatchesAD_get_value_accessor`, flcs, catches, quant, year, unit, season, area, iter)
}

test_FLCatchesAD_set_single_index_accessor <- function(flcs, element, flc) {
    .Call(`_FLasherTests_test_FLCatchesAD_set_single_index_accessor`, flcs, element, flc)
}

test_FLCatchesAD_set_value_accessor <- function(flcs, element, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLCatchesAD_set_value_accessor`, flcs, element, quant, year, unit, season, area, iter, value)
}

test_FLCatchesAD_const_iterator <- function(catches) {
    .Call(`_FLasherTests_test_FLCatchesAD_const_iterator`, catches)
}

test_FLCatchesAD_iterator <- function(catches, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLCatchesAD_iterator`, catches, quant, year, unit, season, area, iter, value)
}

test_FLFishery_empty_constructor <- function() {
    invisible(.Call(`_FLasherTests_test_FLFishery_empty_constructor`))
}

test_simple_FLFishery_sexp_constructor <- function(flf_sexp) {
    .Call(`_FLasherTests_test_simple_FLFishery_sexp_constructor`, flf_sexp)
}

test_FLFishery_sexp_constructor <- function(flf_sexp) {
    .Call(`_FLasherTests_test_FLFishery_sexp_constructor`, flf_sexp)
}

test_FLFishery_as_wrap <- function(flf) {
    .Call(`_FLasherTests_test_FLFishery_as_wrap`, flf)
}

test_FLFishery_copy_constructor <- function(flf1) {
    .Call(`_FLasherTests_test_FLFishery_copy_constructor`, flf1)
}

test_FLFishery_assignment_operator <- function(flf1) {
    .Call(`_FLasherTests_test_FLFishery_assignment_operator`, flf1)
}

test_FLFishery_const_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLFishery_const_catches_get_accessors`, flf, catches, quant, year, unit, season, area, iter)
}

test_FLFishery_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLFishery_catches_get_accessors`, flf, catches, quant, year, unit, season, area, iter)
}

test_FLFishery_const_economics_get_accessors <- function(flf, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLFishery_const_economics_get_accessors`, flf, year, unit, season, area, iter)
}

test_FLFishery_const_get_hperiod <- function(flf, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLFishery_const_get_hperiod`, flf, quant, year, unit, season, area, iter)
}

test_FLFishery_get_hperiod <- function(flf, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLFishery_get_hperiod`, flf, quant, year, unit, season, area, iter)
}

test_FLFishery_set_hperiod <- function(flf, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLFishery_set_hperiod`, flf, quant, year, unit, season, area, iter, value)
}

test_FLFishery_get_effort_subset <- function(flf, indices_min, indices_max) {
    .Call(`_FLasherTests_test_FLFishery_get_effort_subset`, flf, indices_min, indices_max)
}

test_FLFishery_get_effort <- function(flf) {
    .Call(`_FLasherTests_test_FLFishery_get_effort`, flf)
}

test_FLFishery_economics_get_accessors <- function(flf, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLFishery_economics_get_accessors`, flf, year, unit, season, area, iter)
}

test_FLFishery_set_accessors <- function(flf, catches, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLFishery_set_accessors`, flf, catches, quant, year, unit, season, area, iter, value)
}

test_FLFishery_copy_constructor2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLFishery_copy_constructor2`, flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFishery_assignment_operator2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLFishery_assignment_operator2`, flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFisheryAD_empty_constructor <- function() {
    invisible(.Call(`_FLasherTests_test_FLFisheryAD_empty_constructor`))
}

test_simple_FLFisheryAD_sexp_constructor <- function(flf_sexp) {
    .Call(`_FLasherTests_test_simple_FLFisheryAD_sexp_constructor`, flf_sexp)
}

test_FLFisheryAD_sexp_constructor <- function(flf_sexp) {
    .Call(`_FLasherTests_test_FLFisheryAD_sexp_constructor`, flf_sexp)
}

test_FLFisheryAD_as_wrap <- function(flf) {
    .Call(`_FLasherTests_test_FLFisheryAD_as_wrap`, flf)
}

test_FLFisheryAD_copy_constructor <- function(flf1) {
    .Call(`_FLasherTests_test_FLFisheryAD_copy_constructor`, flf1)
}

test_FLFisheryAD_assignment_operator <- function(flf1) {
    .Call(`_FLasherTests_test_FLFisheryAD_assignment_operator`, flf1)
}

test_FLFisheryAD_const_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLFisheryAD_const_catches_get_accessors`, flf, catches, quant, year, unit, season, area, iter)
}

test_FLFisheryAD_catches_get_accessors <- function(flf, catches, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLFisheryAD_catches_get_accessors`, flf, catches, quant, year, unit, season, area, iter)
}

test_FLFisheryAD_const_economics_get_accessors <- function(flf, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLFisheryAD_const_economics_get_accessors`, flf, year, unit, season, area, iter)
}

test_FLFisheryAD_economics_get_accessors <- function(flf, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLFisheryAD_economics_get_accessors`, flf, year, unit, season, area, iter)
}

test_FLFisheryAD_set_accessors <- function(flf, catches, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLFisheryAD_set_accessors`, flf, catches, quant, year, unit, season, area, iter, value)
}

test_FLFisheryAD_copy_constructor2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLFisheryAD_copy_constructor2`, flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFisheryAD_assignment_operator2 <- function(flf1, element, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLFisheryAD_assignment_operator2`, flf1, element, quant, year, unit, season, area, iter, value)
}

test_FLFisheryAD_const_iterator <- function(fishery) {
    .Call(`_FLasherTests_test_FLFisheryAD_const_iterator`, fishery)
}

test_FLFisheryAD_iterator <- function(fishery, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLFisheryAD_iterator`, fishery, quant, year, unit, season, area, iter, value)
}

test_FLFisheries_sexp_constructor <- function(flfs_sexp1) {
    .Call(`_FLasherTests_test_FLFisheries_sexp_constructor`, flfs_sexp1)
}

test_FLFisheries_as_wrap <- function(flfs) {
    .Call(`_FLasherTests_test_FLFisheries_as_wrap`, flfs)
}

test_FLFisheries_get_nfisheries <- function(flfs) {
    .Call(`_FLasherTests_test_FLFisheries_get_nfisheries`, flfs)
}

test_FLFisheries_copy_constructor <- function(flfs) {
    .Call(`_FLasherTests_test_FLFisheries_copy_constructor`, flfs)
}

test_FLFisheries_copy_constructor2 <- function(flfs1, fishery, catches, indices, value) {
    .Call(`_FLasherTests_test_FLFisheries_copy_constructor2`, flfs1, fishery, catches, indices, value)
}

test_FLFisheries_assignment_operator <- function(flfs) {
    .Call(`_FLasherTests_test_FLFisheries_assignment_operator`, flfs)
}

test_FLFisheries_assignment_operator2 <- function(flfs1, fishery, catches, indices, value) {
    .Call(`_FLasherTests_test_FLFisheries_assignment_operator2`, flfs1, fishery, catches, indices, value)
}

test_FLFisheries_const_get_single <- function(flfs, fishery, catches, indices) {
    .Call(`_FLasherTests_test_FLFisheries_const_get_single`, flfs, fishery, catches, indices)
}

test_FLFisheries_get_single <- function(flfs, fishery, catches, indices) {
    .Call(`_FLasherTests_test_FLFisheries_get_single`, flfs, fishery, catches, indices)
}

test_FLFisheries_const_get_double <- function(flfs, fishery, catches, indices) {
    .Call(`_FLasherTests_test_FLFisheries_const_get_double`, flfs, fishery, catches, indices)
}

test_FLFisheries_get_double <- function(flfs, fishery, catches, indices) {
    .Call(`_FLasherTests_test_FLFisheries_get_double`, flfs, fishery, catches, indices)
}

test_FLFisheries_set_single <- function(flfs, fishery, catches, indices, value) {
    .Call(`_FLasherTests_test_FLFisheries_set_single`, flfs, fishery, catches, indices, value)
}

test_FLFisheries_set_double <- function(flfs, fishery, catches, indices, value) {
    .Call(`_FLasherTests_test_FLFisheries_set_double`, flfs, fishery, catches, indices, value)
}

test_FLFishery_revenue <- function(flf) {
    .Call(`_FLasherTests_test_FLFishery_revenue`, flf)
}

test_FLFishery_revenue_subset <- function(flf, indices_min, indices_max) {
    .Call(`_FLasherTests_test_FLFishery_revenue_subset`, flf, indices_min, indices_max)
}

test_FLFisheriesAD_sexp_constructor <- function(flfs_sexp1) {
    .Call(`_FLasherTests_test_FLFisheriesAD_sexp_constructor`, flfs_sexp1)
}

test_FLFisheriesAD_as_wrap <- function(flfs) {
    .Call(`_FLasherTests_test_FLFisheriesAD_as_wrap`, flfs)
}

test_FLFisheriesAD_get_nfisheries <- function(flfs) {
    .Call(`_FLasherTests_test_FLFisheriesAD_get_nfisheries`, flfs)
}

test_FLFisheriesAD_copy_constructor <- function(flfs) {
    .Call(`_FLasherTests_test_FLFisheriesAD_copy_constructor`, flfs)
}

test_FLFisheriesAD_copy_constructor2 <- function(flfs1, fishery, catches, indices, value) {
    .Call(`_FLasherTests_test_FLFisheriesAD_copy_constructor2`, flfs1, fishery, catches, indices, value)
}

test_FLFisheriesAD_assignment_operator <- function(flfs) {
    .Call(`_FLasherTests_test_FLFisheriesAD_assignment_operator`, flfs)
}

test_FLFisheriesAD_assignment_operator2 <- function(flfs1, fishery, catches, indices, value) {
    .Call(`_FLasherTests_test_FLFisheriesAD_assignment_operator2`, flfs1, fishery, catches, indices, value)
}

test_FLFisheriesAD_const_get_single <- function(flfs, fishery, catches, indices) {
    .Call(`_FLasherTests_test_FLFisheriesAD_const_get_single`, flfs, fishery, catches, indices)
}

test_FLFisheriesAD_get_single <- function(flfs, fishery, catches, indices) {
    .Call(`_FLasherTests_test_FLFisheriesAD_get_single`, flfs, fishery, catches, indices)
}

test_FLFisheriesAD_const_get_double <- function(flfs, fishery, catches, indices) {
    .Call(`_FLasherTests_test_FLFisheriesAD_const_get_double`, flfs, fishery, catches, indices)
}

test_FLFisheriesAD_get_double <- function(flfs, fishery, catches, indices) {
    .Call(`_FLasherTests_test_FLFisheriesAD_get_double`, flfs, fishery, catches, indices)
}

test_FLFisheriesAD_set_single <- function(flfs, fishery, catches, indices, value) {
    .Call(`_FLasherTests_test_FLFisheriesAD_set_single`, flfs, fishery, catches, indices, value)
}

test_FLFisheriesAD_set_double <- function(flfs, fishery, catches, indices, value) {
    .Call(`_FLasherTests_test_FLFisheriesAD_set_double`, flfs, fishery, catches, indices, value)
}

test_FLFisheriesAD_const_iterator <- function(fisheries) {
    .Call(`_FLasherTests_test_FLFisheriesAD_const_iterator`, fisheries)
}

test_FLFisheriesAD_iterator <- function(fisheries, value) {
    .Call(`_FLasherTests_test_FLFisheriesAD_iterator`, fisheries, value)
}

test_FLQuantAD_as_wrap <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_as_wrap`, flq)
}

test_FLQuantAD_basic_constructor <- function() {
    invisible(.Call(`_FLasherTests_test_FLQuantAD_basic_constructor`))
}

test_FLQuantAD_sexp_constructor <- function(flq_sexp) {
    .Call(`_FLasherTests_test_FLQuantAD_sexp_constructor`, flq_sexp)
}

test_FLQuantAD_dim_constructor <- function(nquant, nyear, nunit, nseason, narea, niter) {
    .Call(`_FLasherTests_test_FLQuantAD_dim_constructor`, nquant, nyear, nunit, nseason, narea, niter)
}

test_FLQuantAD_copy_constructor <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_copy_constructor`, flq)
}

test_FLQuantAD_copy_constructor2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuantAD_copy_constructor2`, flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuantAD_assignment_operator <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_assignment_operator`, flq)
}

test_FLQuantAD_assignment_operator2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuantAD_assignment_operator2`, flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuantAD_from_FLQuant_constructor <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_from_FLQuant_constructor`, flq)
}

test_FLQuantAD_get_units <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_get_units`, flq)
}

test_FLQuantAD_get_dim <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_get_dim`, flq)
}

test_FLQuantAD_get_dimnames <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_get_dimnames`, flq)
}

test_FLQuantAD_get_size <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_get_size`, flq)
}

test_FLQuantAD_get_nquant <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_get_nquant`, flq)
}

test_FLQuantAD_get_nyear <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_get_nyear`, flq)
}

test_FLQuantAD_get_nunit <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_get_nunit`, flq)
}

test_FLQuantAD_get_nseason <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_get_nseason`, flq)
}

test_FLQuantAD_get_narea <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_get_narea`, flq)
}

test_FLQuantAD_get_niter <- function(flq) {
    .Call(`_FLasherTests_test_FLQuantAD_get_niter`, flq)
}

test_FLQuantAD_get_data_element <- function(flq, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuantAD_get_data_element`, flq, quant, year, unit, season, area, iter)
}

test_FLQuantAD_get_const_single_index_accessor <- function(flq, element) {
    .Call(`_FLasherTests_test_FLQuantAD_get_const_single_index_accessor`, flq, element)
}

test_FLQuantAD_get_single_index_accessor <- function(flq, element) {
    .Call(`_FLasherTests_test_FLQuantAD_get_single_index_accessor`, flq, element)
}

test_FLQuantAD_set_single_index_accessor <- function(flq, element, value) {
    .Call(`_FLasherTests_test_FLQuantAD_set_single_index_accessor`, flq, element, value)
}

test_FLQuantAD_const_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuantAD_const_get_accessor`, flq, quant, year, unit, season, area, iter)
}

test_FLQuantAD_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuantAD_get_accessor`, flq, quant, year, unit, season, area, iter)
}

test_FLQuantAD_set_accessor <- function(flq, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuantAD_set_accessor`, flq, quant, year, unit, season, area, iter, value)
}

test_FLQuantAD_get_const_indices_accessor <- function(flq, indices) {
    .Call(`_FLasherTests_test_FLQuantAD_get_const_indices_accessor`, flq, indices)
}

test_FLQuantAD_get_indices_accessor <- function(flq, indices) {
    .Call(`_FLasherTests_test_FLQuantAD_get_indices_accessor`, flq, indices)
}

test_FLQuantAD_set_indices_accessor <- function(flq, indices, value) {
    .Call(`_FLasherTests_test_FLQuantAD_set_indices_accessor`, flq, indices, value)
}

test_FLQuantAD_set_dimnames <- function(flq, new_dimnames) {
    .Call(`_FLasherTests_test_FLQuantAD_set_dimnames`, flq, new_dimnames)
}

test_FLQuantAD_FLQuantAD_match_dims <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuantAD_match_dims`, flq1, flq2)
}

test_FLQuantAD_FLQuant_match_dims <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuantAD_FLQuant_match_dims`, flq1, flq2)
}

test_FLQuant_FLQuantAD_match_dims <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuantAD_match_dims`, flq1, flq2)
}

test_FLQuantAD_fill <- function(flq, value) {
    .Call(`_FLasherTests_test_FLQuantAD_fill`, flq, value)
}

test_FLQuantAD_fill_double <- function(flq, value) {
    .Call(`_FLasherTests_test_FLQuantAD_fill_double`, flq, value)
}

testFLCppAD <- function(scalar) {
    invisible(.Call(`_FLasherTests_testFLCppAD`, scalar))
}

FLPar_units <- function(flp) {
    .Call(`_FLasherTests_FLPar_units`, flp)
}

test_FLQuant_as_wrap <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_as_wrap`, flq)
}

test_FLQuant_basic_constructor <- function() {
    invisible(.Call(`_FLasherTests_test_FLQuant_basic_constructor`))
}

test_FLQuant_sexp_constructor <- function(flq_sexp) {
    .Call(`_FLasherTests_test_FLQuant_sexp_constructor`, flq_sexp)
}

test_FLQuant_dim_constructor <- function(nquant, nyear, nunit, nseason, narea, niter) {
    .Call(`_FLasherTests_test_FLQuant_dim_constructor`, nquant, nyear, nunit, nseason, narea, niter)
}

test_FLQuant_dim_value_constructor <- function(nquant, nyear, nunit, nseason, narea, niter, value) {
    .Call(`_FLasherTests_test_FLQuant_dim_value_constructor`, nquant, nyear, nunit, nseason, narea, niter, value)
}

test_FLQuant_intvec_dim_constructor <- function(dims) {
    .Call(`_FLasherTests_test_FLQuant_intvec_dim_constructor`, dims)
}

test_FLQuant_intvec_dim_value_constructor <- function(dims, value) {
    .Call(`_FLasherTests_test_FLQuant_intvec_dim_value_constructor`, dims, value)
}

test_FLQuant_copy_constructor <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_copy_constructor`, flq)
}

test_FLQuant_copy_constructor2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuant_copy_constructor2`, flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuant_assignment_operator <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_assignment_operator`, flq)
}

test_FLQuant_assignment_operator2 <- function(flq1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuant_assignment_operator2`, flq1, quant, year, unit, season, area, iter, value)
}

test_FLQuant_from_FLQuantAD_constructor <- function(flqad) {
    .Call(`_FLasherTests_test_FLQuant_from_FLQuantAD_constructor`, flqad)
}

test_FLQuant_get_data <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_data`, flq)
}

test_FLQuant_get_units <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_units`, flq)
}

test_FLQuant_get_dim <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_dim`, flq)
}

test_FLQuant_get_dimnames <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_dimnames`, flq)
}

test_FLQuant_get_dimnames2 <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_dimnames2`, flq)
}

test_FLQuant_get_size <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_size`, flq)
}

test_FLQuant_get_nquant <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_nquant`, flq)
}

test_FLQuant_get_nyear <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_nyear`, flq)
}

test_FLQuant_get_nunit <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_nunit`, flq)
}

test_FLQuant_get_nseason <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_nseason`, flq)
}

test_FLQuant_get_narea <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_narea`, flq)
}

test_FLQuant_get_niter <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_niter`, flq)
}

test_FLQuant_get_first_age <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant_get_first_age`, flq)
}

test_FLQuant_get_data_element <- function(flq, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuant_get_data_element`, flq, quant, year, unit, season, area, iter)
}

test_FLQuant_get_const_single_index_accessor <- function(flq, element) {
    .Call(`_FLasherTests_test_FLQuant_get_const_single_index_accessor`, flq, element)
}

test_FLQuant_get_single_index_accessor <- function(flq, element) {
    .Call(`_FLasherTests_test_FLQuant_get_single_index_accessor`, flq, element)
}

test_FLQuant_set_single_index_accessor <- function(flq, element, value) {
    .Call(`_FLasherTests_test_FLQuant_set_single_index_accessor`, flq, element, value)
}

test_FLQuant_const_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuant_const_get_accessor`, flq, quant, year, unit, season, area, iter)
}

test_FLQuant_get_accessor <- function(flq, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuant_get_accessor`, flq, quant, year, unit, season, area, iter)
}

test_FLQuant_set_accessor <- function(flq, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuant_set_accessor`, flq, quant, year, unit, season, area, iter, value)
}

test_FLQuant_get_const_indices_accessor <- function(flq, indices) {
    .Call(`_FLasherTests_test_FLQuant_get_const_indices_accessor`, flq, indices)
}

test_FLQuant_get_indices_accessor <- function(flq, indices) {
    .Call(`_FLasherTests_test_FLQuant_get_indices_accessor`, flq, indices)
}

test_FLQuant_set_indices_accessor <- function(flq, indices, value) {
    .Call(`_FLasherTests_test_FLQuant_set_indices_accessor`, flq, indices, value)
}

test_FLQuant_get_all_iters <- function(flq, quant, year, unit, season, area) {
    .Call(`_FLasherTests_test_FLQuant_get_all_iters`, flq, quant, year, unit, season, area)
}

test_FLQuant_set_data <- function(flq, data_in) {
    .Call(`_FLasherTests_test_FLQuant_set_data`, flq, data_in)
}

test_FLQuant_set_dimnames <- function(flq, new_dimnames) {
    .Call(`_FLasherTests_test_FLQuant_set_dimnames`, flq, new_dimnames)
}

test_FLQuant_set_units <- function(flq, new_units) {
    .Call(`_FLasherTests_test_FLQuant_set_units`, flq, new_units)
}

test_FLQuant_subset <- function(flq, quant_min, quant_max, year_min, year_max, unit_min, unit_max, season_min, season_max, area_min, area_max, iter_min, iter_max) {
    .Call(`_FLasherTests_test_FLQuant_subset`, flq, quant_min, quant_max, year_min, year_max, unit_min, unit_max, season_min, season_max, area_min, area_max, iter_min, iter_max)
}

test_FLQuant_neat_subset <- function(flq, indices_min, indices_max) {
    .Call(`_FLasherTests_test_FLQuant_neat_subset`, flq, indices_min, indices_max)
}

test_FLQuant_propagate_iters <- function(flq, iters) {
    .Call(`_FLasherTests_test_FLQuant_propagate_iters`, flq, iters)
}

test_FLQuant_fill <- function(flq, value) {
    .Call(`_FLasherTests_test_FLQuant_fill`, flq, value)
}

test_FLQuant_FLQuant_match_dims <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuant_FLQuant_match_dims`, flq1, flq2)
}

test_FLPar_to_FLQuant <- function(flp) {
    .Call(`_FLasherTests_test_FLPar_to_FLQuant`, flp)
}

test_for_range <- function(flq, rn) {
    .Call(`_FLasherTests_test_for_range`, flq, rn)
}

test_for_range_const <- function(flq, rn) {
    .Call(`_FLasherTests_test_for_range_const`, flq, rn)
}

test_FLQuant_for_iterator <- function(flq, rn) {
    .Call(`_FLasherTests_test_FLQuant_for_iterator`, flq, rn)
}

test_FLQuant_for_iterator_const <- function(flq, rn) {
    .Call(`_FLasherTests_test_FLQuant_for_iterator_const`, flq, rn)
}

test_FLQuant_lambda <- function(flq1, flq2) {
    .Call(`_FLasherTests_test_FLQuant_lambda`, flq1, flq2)
}

test_DD_pow <- function(flq, power) {
    .Call(`_FLasherTests_test_DD_pow`, flq, power)
}

test_DAD_pow <- function(flq, power) {
    .Call(`_FLasherTests_test_DAD_pow`, flq, power)
}

test_ADD_pow <- function(flq, power) {
    .Call(`_FLasherTests_test_ADD_pow`, flq, power)
}

test_ADAD_pow <- function(flq, power) {
    .Call(`_FLasherTests_test_ADAD_pow`, flq, power)
}

test_input_subsetter_ADAD <- function(flq1, flq2, indices_min, indices_max) {
    .Call(`_FLasherTests_test_input_subsetter_ADAD`, flq1, flq2, indices_min, indices_max)
}

test_input_subsetter_DD <- function(flq1, flq2, indices_min, indices_max) {
    .Call(`_FLasherTests_test_input_subsetter_DD`, flq1, flq2, indices_min, indices_max)
}

test_input_subsetter_ADD <- function(flq1, flq2, indices_min, indices_max) {
    .Call(`_FLasherTests_test_input_subsetter_ADD`, flq1, flq2, indices_min, indices_max)
}

test_input_subsetter_DAD <- function(flq1, flq2, indices_min, indices_max) {
    .Call(`_FLasherTests_test_input_subsetter_DAD`, flq1, flq2, indices_min, indices_max)
}

test_year_season_to_timestep_FLQuant_double <- function(flq, year, season) {
    .Call(`_FLasherTests_test_year_season_to_timestep_FLQuant_double`, flq, year, season)
}

test_year_season_to_timestep_FLQuant_adouble <- function(flqad, year, season) {
    .Call(`_FLasherTests_test_year_season_to_timestep_FLQuant_adouble`, flqad, year, season)
}

test_year_season_to_timestep <- function(flq, year, season) {
    .Call(`_FLasherTests_test_year_season_to_timestep`, flq, year, season)
}

test_timestep_to_year_season_FLQuant_double <- function(flq, timestep) {
    .Call(`_FLasherTests_test_timestep_to_year_season_FLQuant_double`, flq, timestep)
}

test_timestep_to_year_season_FLQuant_adouble <- function(flqad, timestep) {
    .Call(`_FLasherTests_test_timestep_to_year_season_FLQuant_adouble`, flqad, timestep)
}

test_timestep_to_year_season <- function(flq, timestep) {
    .Call(`_FLasherTests_test_timestep_to_year_season`, flq, timestep)
}

test_FLQuant7_as_wrap <- function(flq7) {
    .Call(`_FLasherTests_test_FLQuant7_as_wrap`, flq7)
}

test_FLQuant7_empty_wrap <- function() {
    .Call(`_FLasherTests_test_FLQuant7_empty_wrap`)
}

test_FLQuant7_basic_constructor <- function() {
    invisible(.Call(`_FLasherTests_test_FLQuant7_basic_constructor`))
}

test_FLQuant7_sexp_constructor <- function(flq_sexp1) {
    .Call(`_FLasherTests_test_FLQuant7_sexp_constructor`, flq_sexp1)
}

test_FLQuant7_FLQuant_constructor <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant7_FLQuant_constructor`, flq)
}

test_FLQuant7_copy_constructor <- function(flq7) {
    .Call(`_FLasherTests_test_FLQuant7_copy_constructor`, flq7)
}

test_FLQuant7_copy_constructor2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuant7_copy_constructor2`, flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7_assignment_operator <- function(flq7) {
    .Call(`_FLasherTests_test_FLQuant7_assignment_operator`, flq7)
}

test_FLQuant7_assignment_operator2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuant7_assignment_operator2`, flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7_function_operator <- function(flq7, flq) {
    .Call(`_FLasherTests_test_FLQuant7_function_operator`, flq7, flq)
}

test_FLQuant7_get_ndim7 <- function(flq_sexp1) {
    .Call(`_FLasherTests_test_FLQuant7_get_ndim7`, flq_sexp1)
}

test_FLQuant7_const_get_single_index_accessor <- function(flq7, element) {
    .Call(`_FLasherTests_test_FLQuant7_const_get_single_index_accessor`, flq7, element)
}

test_FLQuant7_get_single_index_accessor <- function(flq7, element) {
    .Call(`_FLasherTests_test_FLQuant7_get_single_index_accessor`, flq7, element)
}

test_FLQuant7_set_single_index_accessor <- function(flq7, element, flq) {
    .Call(`_FLasherTests_test_FLQuant7_set_single_index_accessor`, flq7, element, flq)
}

test_FLQuant7_const_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuant7_const_get_accessor`, flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuant7_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuant7_get_accessor`, flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuant7_set_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuant7_set_accessor`, flq7, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7_const_default_dim7_get_accessor <- function(flq7) {
    .Call(`_FLasherTests_test_FLQuant7_const_default_dim7_get_accessor`, flq7)
}

test_FLQuant7_default_dim7_get_accessor <- function(flq7) {
    .Call(`_FLasherTests_test_FLQuant7_default_dim7_get_accessor`, flq7)
}

test_FLQuant7_default_dim7_set_accessor <- function(flq7, flq) {
    .Call(`_FLasherTests_test_FLQuant7_default_dim7_set_accessor`, flq7, flq)
}

test_FLQuant7_const_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuant7_const_default_dim7_get_accessor_multi`, flq7, quant, year, unit, season, area, iter)
}

test_FLQuant7_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuant7_default_dim7_get_accessor_multi`, flq7, quant, year, unit, season, area, iter)
}

test_FLQuant7_default_dim7_set_accessor_multi <- function(flq7, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuant7_default_dim7_set_accessor_multi`, flq7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7AD_as_wrap <- function(flq7) {
    .Call(`_FLasherTests_test_FLQuant7AD_as_wrap`, flq7)
}

test_FLQuant7AD_empty_wrap <- function() {
    .Call(`_FLasherTests_test_FLQuant7AD_empty_wrap`)
}

test_FLQuant7AD_basic_constructor <- function() {
    invisible(.Call(`_FLasherTests_test_FLQuant7AD_basic_constructor`))
}

test_FLQuant7AD_sexp_constructor <- function(flq_sexp1) {
    .Call(`_FLasherTests_test_FLQuant7AD_sexp_constructor`, flq_sexp1)
}

test_FLQuant7AD_FLQuant_constructor <- function(flq) {
    .Call(`_FLasherTests_test_FLQuant7AD_FLQuant_constructor`, flq)
}

test_FLQuant7AD_copy_constructor <- function(flq7) {
    .Call(`_FLasherTests_test_FLQuant7AD_copy_constructor`, flq7)
}

test_FLQuant7AD_copy_constructor2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuant7AD_copy_constructor2`, flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7AD_assignment_operator <- function(flq7) {
    .Call(`_FLasherTests_test_FLQuant7AD_assignment_operator`, flq7)
}

test_FLQuant7AD_assignment_operator2 <- function(flq71, dim7, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuant7AD_assignment_operator2`, flq71, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7AD_function_operator <- function(flq7, flq) {
    .Call(`_FLasherTests_test_FLQuant7AD_function_operator`, flq7, flq)
}

test_FLQuant7AD_get_ndim7 <- function(flq_sexp1) {
    .Call(`_FLasherTests_test_FLQuant7AD_get_ndim7`, flq_sexp1)
}

test_FLQuant7AD_const_get_single_index_accessor <- function(flq7, element) {
    .Call(`_FLasherTests_test_FLQuant7AD_const_get_single_index_accessor`, flq7, element)
}

test_FLQuant7AD_get_single_index_accessor <- function(flq7, element) {
    .Call(`_FLasherTests_test_FLQuant7AD_get_single_index_accessor`, flq7, element)
}

test_FLQuant7AD_set_single_index_accessor <- function(flq7, element, flq) {
    .Call(`_FLasherTests_test_FLQuant7AD_set_single_index_accessor`, flq7, element, flq)
}

test_FLQuant7AD_const_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuant7AD_const_get_accessor`, flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuant7AD_get_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuant7AD_get_accessor`, flq7, dim7, quant, year, unit, season, area, iter)
}

test_FLQuant7AD_set_accessor <- function(flq7, dim7, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuant7AD_set_accessor`, flq7, dim7, quant, year, unit, season, area, iter, value)
}

test_FLQuant7AD_const_default_dim7_get_accessor <- function(flq7) {
    .Call(`_FLasherTests_test_FLQuant7AD_const_default_dim7_get_accessor`, flq7)
}

test_FLQuant7AD_default_dim7_get_accessor <- function(flq7) {
    .Call(`_FLasherTests_test_FLQuant7AD_default_dim7_get_accessor`, flq7)
}

test_FLQuant7AD_default_dim7_set_accessor <- function(flq7, flq) {
    .Call(`_FLasherTests_test_FLQuant7AD_default_dim7_set_accessor`, flq7, flq)
}

test_FLQuant7AD_const_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuant7AD_const_default_dim7_get_accessor_multi`, flq7, quant, year, unit, season, area, iter)
}

test_FLQuant7AD_default_dim7_get_accessor_multi <- function(flq7, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_FLQuant7AD_default_dim7_get_accessor_multi`, flq7, quant, year, unit, season, area, iter)
}

test_FLQuant7AD_default_dim7_set_accessor_multi <- function(flq7, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLQuant7AD_default_dim7_set_accessor_multi`, flq7, quant, year, unit, season, area, iter, value)
}

test_FLQ_in_FLS <- function(flq) {
    .Call(`_FLasherTests_test_FLQ_in_FLS`, flq)
}

test_FLStock_sexp_constructor <- function(fls_sexp) {
    .Call(`_FLasherTests_test_FLStock_sexp_constructor`, fls_sexp)
}

test_FLStock_wrap <- function(fls_sexp) {
    .Call(`_FLasherTests_test_FLStock_wrap`, fls_sexp)
}

test_FLStock_as <- function(fls) {
    .Call(`_FLasherTests_test_FLStock_as`, fls)
}

test_FLStock_as_wrap <- function(fls) {
    .Call(`_FLasherTests_test_FLStock_as_wrap`, fls)
}

test_FLStock_copy_constructor <- function(fls1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLStock_copy_constructor`, fls1, quant, year, unit, season, area, iter, value)
}

test_FLStock_assignment_operator <- function(fls1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_FLStock_assignment_operator`, fls1, quant, year, unit, season, area, iter, value)
}

test_fwdBiol_sexp_constructor <- function(flb_sexp) {
    .Call(`_FLasherTests_test_fwdBiol_sexp_constructor`, flb_sexp)
}

test_fwdBiolAD_sexp_constructor <- function(flb_sexp) {
    .Call(`_FLasherTests_test_fwdBiolAD_sexp_constructor`, flb_sexp)
}

test_fwdBiol_as_wrap <- function(fwdb) {
    .Call(`_FLasherTests_test_fwdBiol_as_wrap`, fwdb)
}

test_fwdBiolAD_as_wrap <- function(fwdb) {
    .Call(`_FLasherTests_test_fwdBiolAD_as_wrap`, fwdb)
}

test_fwdBiol_fwdSR_constructor <- function(flb_sexp, model_name, params, residuals, residuals_mult) {
    .Call(`_FLasherTests_test_fwdBiol_fwdSR_constructor`, flb_sexp, model_name, params, residuals, residuals_mult)
}

test_fwdBiolAD_fwdSRAD_constructor <- function(flb_sexp, model_name, params, residuals, residuals_mult) {
    .Call(`_FLasherTests_test_fwdBiolAD_fwdSRAD_constructor`, flb_sexp, model_name, params, residuals, residuals_mult)
}

test_fwdBiol_FLSR_bits_constructor <- function(flb_sexp, model_name, params, residuals, residuals_mult) {
    .Call(`_FLasherTests_test_fwdBiol_FLSR_bits_constructor`, flb_sexp, model_name, params, residuals, residuals_mult)
}

test_fwdBiolAD_FLSR_residuals_constructor <- function(flb_sexp, residuals, residuals_mult) {
    .Call(`_FLasherTests_test_fwdBiolAD_FLSR_residuals_constructor`, flb_sexp, residuals, residuals_mult)
}

test_fwdBiolAD_FLSR_bits_constructor <- function(flb_sexp, model_name, params, residuals, residuals_mult) {
    .Call(`_FLasherTests_test_fwdBiolAD_FLSR_bits_constructor`, flb_sexp, model_name, params, residuals, residuals_mult)
}

test_fwdBiol_copy_constructor <- function(fwdb1) {
    .Call(`_FLasherTests_test_fwdBiol_copy_constructor`, fwdb1)
}

test_fwdBiolAD_copy_constructor <- function(fwdb1) {
    .Call(`_FLasherTests_test_fwdBiolAD_copy_constructor`, fwdb1)
}

test_fwdBiol_copy_constructor2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_fwdBiol_copy_constructor2`, fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiolAD_copy_constructor2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_fwdBiolAD_copy_constructor2`, fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiol_assignment_operator <- function(fwdb1) {
    .Call(`_FLasherTests_test_fwdBiol_assignment_operator`, fwdb1)
}

test_fwdBiolAD_assignment_operator <- function(fwdb1) {
    .Call(`_FLasherTests_test_fwdBiolAD_assignment_operator`, fwdb1)
}

test_fwdBiol_assignment_operator2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_fwdBiol_assignment_operator2`, fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiolAD_assignment_operator2 <- function(fwdb1, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_fwdBiolAD_assignment_operator2`, fwdb1, quant, year, unit, season, area, iter, value)
}

test_fwdBiol_const_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_fwdBiol_const_get_accessors`, fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiol_const_get_accessors_subset <- function(fwdb, indices_min, indices_max) {
    .Call(`_FLasherTests_test_fwdBiol_const_get_accessors_subset`, fwdb, indices_min, indices_max)
}

test_fwdBiol_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_fwdBiol_get_accessors`, fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiolAD_const_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_fwdBiolAD_const_get_accessors`, fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiolAD_get_accessors <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_fwdBiolAD_get_accessors`, fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiol_set_accessors <- function(fwdb, quant, year, unit, season, area, iter, values) {
    .Call(`_FLasherTests_test_fwdBiol_set_accessors`, fwdb, quant, year, unit, season, area, iter, values)
}

test_fwdBiolAD_set_accessors <- function(fwdb, quant, year, unit, season, area, iter, values) {
    .Call(`_FLasherTests_test_fwdBiolAD_set_accessors`, fwdb, quant, year, unit, season, area, iter, values)
}

fwdBiolAD_biomass_FLQ <- function(fwdb) {
    .Call(`_FLasherTests_fwdBiolAD_biomass_FLQ`, fwdb)
}

fwdBiolAD_biomass_subset <- function(fwdb, indices_min, indices_max) {
    .Call(`_FLasherTests_fwdBiolAD_biomass_subset`, fwdb, indices_min, indices_max)
}

test_fwdBiolAD_n_direct_set_accessor <- function(fwdb, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_fwdBiolAD_n_direct_set_accessor`, fwdb, quant, year, unit, season, area, iter, value)
}

test_fwdBiolAD_n_direct_get_accessor <- function(fwdb, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_fwdBiolAD_n_direct_get_accessor`, fwdb, quant, year, unit, season, area, iter)
}

test_fwdBiol_srp_timelag <- function(fwb) {
    .Call(`_FLasherTests_test_fwdBiol_srp_timelag`, fwb)
}

test_fwdBiols_as_wrap <- function(biols_in) {
    .Call(`_FLasherTests_test_fwdBiols_as_wrap`, biols_in)
}

test_fwdBiolsAD_as_wrap <- function(biols_in) {
    .Call(`_FLasherTests_test_fwdBiolsAD_as_wrap`, biols_in)
}

test_fwdBiolsAD_fwdBiolAD_constructor <- function(flb_sexp, residuals, residuals_mult) {
    .Call(`_FLasherTests_test_fwdBiolsAD_fwdBiolAD_constructor`, flb_sexp, residuals, residuals_mult)
}

test_fwdBiolsAD_const_get_single_index_accessor <- function(fwbs, element) {
    .Call(`_FLasherTests_test_fwdBiolsAD_const_get_single_index_accessor`, fwbs, element)
}

test_fwdBiolsAD_get_single_index_accessor <- function(fwbs, element) {
    .Call(`_FLasherTests_test_fwdBiolsAD_get_single_index_accessor`, fwbs, element)
}

test_fwdBiolsAD_const_get_value_accessor <- function(fwbs, biol_no, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_fwdBiolsAD_const_get_value_accessor`, fwbs, biol_no, quant, year, unit, season, area, iter)
}

test_fwdBiolsAD_get_value_accessor <- function(fwbs, biol_no, quant, year, unit, season, area, iter) {
    .Call(`_FLasherTests_test_fwdBiolsAD_get_value_accessor`, fwbs, biol_no, quant, year, unit, season, area, iter)
}

test_fwdBiolsAD_set_single_index_accessor <- function(fwbs, element, flb_sexp, residuals, residuals_mult) {
    .Call(`_FLasherTests_test_fwdBiolsAD_set_single_index_accessor`, fwbs, element, flb_sexp, residuals, residuals_mult)
}

test_fwdBiolsAD_set_value_accessor <- function(fwbs, biol_no, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_fwdBiolsAD_set_value_accessor`, fwbs, biol_no, quant, year, unit, season, area, iter, value)
}

test_fwdBiolsAD_copy_constructor <- function(fwbs1, biol_no, dims, value) {
    .Call(`_FLasherTests_test_fwdBiolsAD_copy_constructor`, fwbs1, biol_no, dims, value)
}

test_fwdBiolsAD_assignment_operator <- function(fwbs1, biol_no, dims, value) {
    .Call(`_FLasherTests_test_fwdBiolsAD_assignment_operator`, fwbs1, biol_no, dims, value)
}

test_fwdBiolsAD_const_iterator <- function(fwbs) {
    .Call(`_FLasherTests_test_fwdBiolsAD_const_iterator`, fwbs)
}

test_fwdBiolsAD_iterator <- function(fwbs, quant, year, unit, season, area, iter, value) {
    .Call(`_FLasherTests_test_fwdBiolsAD_iterator`, fwbs, quant, year, unit, season, area, iter, value)
}

test_as_wrap_fwdControl <- function(control) {
    .Call(`_FLasherTests_test_as_wrap_fwdControl`, control)
}

test_fwdControl_copy_constructor <- function(fc1) {
    .Call(`_FLasherTests_test_fwdControl_copy_constructor`, fc1)
}

test_fwdControl_assignment_operator <- function(fc) {
    .Call(`_FLasherTests_test_fwdControl_assignment_operator`, fc)
}

test_fwdControl_get_target <- function(control) {
    .Call(`_FLasherTests_test_fwdControl_get_target`, control)
}

test_fwdControl_get_ntarget <- function(control) {
    .Call(`_FLasherTests_test_fwdControl_get_ntarget`, control)
}

test_fwdControl_get_niter <- function(control) {
    .Call(`_FLasherTests_test_fwdControl_get_niter`, control)
}

test_fwdControl_get_nsim_target <- function(control, target_no) {
    .Call(`_FLasherTests_test_fwdControl_get_nsim_target`, control, target_no)
}

test_fwdControl_get_target_row <- function(control, target_no, sim_target_no) {
    .Call(`_FLasherTests_test_fwdControl_get_target_row`, control, target_no, sim_target_no)
}

test_fwdControl_get_target_rows <- function(control, target_no) {
    .Call(`_FLasherTests_test_fwdControl_get_target_rows`, control, target_no)
}

test_fwdControl_get_target_int_col <- function(control, target_no, col) {
    .Call(`_FLasherTests_test_fwdControl_get_target_int_col`, control, target_no, col)
}

test_fwdControl_get_target_int_col2 <- function(control, target_no, sim_target_no, col) {
    .Call(`_FLasherTests_test_fwdControl_get_target_int_col2`, control, target_no, sim_target_no, col)
}

test_fwdControl_get_target_list_int_col <- function(control, target_no, col) {
    .Call(`_FLasherTests_test_fwdControl_get_target_list_int_col`, control, target_no, col)
}

test_fwdControl_get_target_list_int_col2 <- function(control, target_no, sim_target_no, col) {
    .Call(`_FLasherTests_test_fwdControl_get_target_list_int_col2`, control, target_no, sim_target_no, col)
}

test_fwdControl_get_target_num_col <- function(control, target_no, col) {
    .Call(`_FLasherTests_test_fwdControl_get_target_num_col`, control, target_no, col)
}

test_fwdControl_get_target_num_col2 <- function(control, target_no, sim_target_no, col) {
    .Call(`_FLasherTests_test_fwdControl_get_target_num_col2`, control, target_no, sim_target_no, col)
}

test_fwdControl_get_target_value <- function(control, target_no, col) {
    .Call(`_FLasherTests_test_fwdControl_get_target_value`, control, target_no, col)
}

test_fwdControl_get_target_value2 <- function(control, target_no, sim_target_no, col) {
    .Call(`_FLasherTests_test_fwdControl_get_target_value2`, control, target_no, sim_target_no, col)
}

test_fwdControl_get_target_quantity <- function(control, target_no, sim_target_no) {
    .Call(`_FLasherTests_test_fwdControl_get_target_quantity`, control, target_no, sim_target_no)
}

test_fwdControl_get_age_range <- function(control, target_no, sim_target_no) {
    .Call(`_FLasherTests_test_fwdControl_get_age_range`, control, target_no, sim_target_no)
}

test_fwdControl_get_FC <- function(control, biol_no) {
    .Call(`_FLasherTests_test_fwdControl_get_FC`, control, biol_no)
}

test_fwdControl_get_B <- function(control, fishery_no, catch_no) {
    .Call(`_FLasherTests_test_fwdControl_get_B`, control, fishery_no, catch_no)
}

test_fwdControl_get_F <- function(control, biol_no) {
    .Call(`_FLasherTests_test_fwdControl_get_F`, control, biol_no)
}

test_fwdControl_get_FCB_nrow <- function(control) {
    .Call(`_FLasherTests_test_fwdControl_get_FCB_nrow`, control)
}

test_fwdControl_get_FCB_row_no <- function(control, fishery_no, catch_no, biol_no) {
    .Call(`_FLasherTests_test_fwdControl_get_FCB_row_no`, control, fishery_no, catch_no, biol_no)
}

test_fwdControl_get_FCB_nos <- function(control, target_no, sim_target_no, relative, check) {
    .Call(`_FLasherTests_test_fwdControl_get_FCB_nos`, control, target_no, sim_target_no, relative, check)
}

test_fwdControl_shared_catch <- function(control, biol_no) {
    .Call(`_FLasherTests_test_fwdControl_shared_catch`, control, biol_no)
}

test_fwdSR_empty_constructor <- function() {
    invisible(.Call(`_FLasherTests_test_fwdSR_empty_constructor`))
}

test_fwdSR_constructor_wrap <- function(model_name, params, residuals, residuals_mult) {
    .Call(`_FLasherTests_test_fwdSR_constructor_wrap`, model_name, params, residuals, residuals_mult)
}

test_fwdSR_get_nparams <- function(model_name, params, residuals, residuals_mult) {
    .Call(`_FLasherTests_test_fwdSR_get_nparams`, model_name, params, residuals, residuals_mult)
}

test_fwdSR_eval <- function(model_name, params, residuals, residuals_mult, srp, param_indices) {
    .Call(`_FLasherTests_test_fwdSR_eval`, model_name, params, residuals, residuals_mult, srp, param_indices)
}

test_fwdSR_get_params <- function(model_name, params, residuals, residuals_mult, param_indices) {
    .Call(`_FLasherTests_test_fwdSR_get_params`, model_name, params, residuals, residuals_mult, param_indices)
}

test_fwdSR_copy_constructor <- function(model_name, params, residuals, residuals_mult, srp) {
    .Call(`_FLasherTests_test_fwdSR_copy_constructor`, model_name, params, residuals, residuals_mult, srp)
}

test_fwdSR_assignment_operator <- function(model_name, params, residuals, residuals_mult, srp) {
    .Call(`_FLasherTests_test_fwdSR_assignment_operator`, model_name, params, residuals, residuals_mult, srp)
}

test_fwdSR_predict_recruitment <- function(model_name, params, residuals, residuals_mult, srp, initial_params_indices) {
    .Call(`_FLasherTests_test_fwdSR_predict_recruitment`, model_name, params, residuals, residuals_mult, srp, initial_params_indices)
}

test_fwdSR_does_recruitment_happen <- function(model_name, params, residuals, residuals_mult, unit, year, season) {
    .Call(`_FLasherTests_test_fwdSR_does_recruitment_happen`, model_name, params, residuals, residuals_mult, unit, year, season)
}

test_operatingModel_empty_constructor <- function() {
    invisible(.Call(`_FLasherTests_test_operatingModel_empty_constructor`))
}

test_operatingModel_full_constructor <- function(flfs, biols, ctrl) {
    .Call(`_FLasherTests_test_operatingModel_full_constructor`, flfs, biols, ctrl)
}

test_operatingModel_get_niter <- function(flfs, biols, ctrl) {
    .Call(`_FLasherTests_test_operatingModel_get_niter`, flfs, biols, ctrl)
}

test_operatingModel_get_exp_z_pre_spwn <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_get_exp_z_pre_spwn`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_f_prop_spwn_FLQ_subset <- function(flfs, biols, ctrl, fishery_no, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_f_prop_spwn_FLQ_subset`, flfs, biols, ctrl, fishery_no, biol_no, indices_min, indices_max)
}

test_operatingModel_SRP_FLQ_subset <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_SRP_FLQ_subset`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_total_SRP_FLQ_subset <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_total_SRP_FLQ_subset`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_calc_rec <- function(flfs, biols, ctrl, biol_no, unit, rec_timestep) {
    .Call(`_FLasherTests_test_operatingModel_calc_rec`, flfs, biols, ctrl, biol_no, unit, rec_timestep)
}

test_operatingModel_get_f_FCB <- function(flfs, biols, ctrl, fishery_no, catch_no, biol_no) {
    .Call(`_FLasherTests_test_operatingModel_get_f_FCB`, flfs, biols, ctrl, fishery_no, catch_no, biol_no)
}

test_operatingModel_get_f_FCB_subset <- function(flfs, biols, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_get_f_FCB_subset`, flfs, biols, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max)
}

test_operatingModel_get_f_B_subset <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_get_f_B_subset`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_get_f_B <- function(flfs, biols, ctrl, biol_no) {
    .Call(`_FLasherTests_test_operatingModel_get_f_B`, flfs, biols, ctrl, biol_no)
}

test_operatingModel_fbar_FCB <- function(flfs, biols, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_fbar_FCB`, flfs, biols, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max)
}

test_operatingModel_fbar_B <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_fbar_B`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_nunit_z_subset <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_nunit_z_subset`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_nunit_f_B_subset <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_nunit_f_B_subset`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_nunit_f_FCB_subset <- function(flfs, biols, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_nunit_f_FCB_subset`, flfs, biols, ctrl, fishery_no, catch_no, biol_no, indices_min, indices_max)
}

test_operatingModel_survivors <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_survivors`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_project_biols <- function(flfs, biols, ctrl, timestep) {
    .Call(`_FLasherTests_test_operatingModel_project_biols`, flfs, biols, ctrl, timestep)
}

test_operatingModel_project_fisheries <- function(flfs, biols, ctrl, timestep) {
    .Call(`_FLasherTests_test_operatingModel_project_fisheries`, flfs, biols, ctrl, timestep)
}

test_operatingModel_run <- function(flfs, biols, ctrl, effort_mult_initial, indep_min, indep_max, nr_iters = 50L) {
    .Call(`_FLasherTests_test_operatingModel_run`, flfs, biols, ctrl, effort_mult_initial, indep_min, indep_max, nr_iters)
}

test_operatingModel_run2 <- function(flfs, biols, ctrl, effort_mult_initial, indep_min, indep_max, nr_iters = 50L) {
    .Call(`_FLasherTests_test_operatingModel_run2`, flfs, biols, ctrl, effort_mult_initial, indep_min, indep_max, nr_iters)
}

test_operatingModel_eval_om <- function(flfs, biols, ctrl, strquantity, fishery_no, catch_no, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_eval_om`, flfs, biols, ctrl, strquantity, fishery_no, catch_no, biol_no, indices_min, indices_max)
}

test_operatingModel_get_target_value_hat <- function(flfs, biols, ctrl, target_no, sim_target_no) {
    .Call(`_FLasherTests_test_operatingModel_get_target_value_hat`, flfs, biols, ctrl, target_no, sim_target_no)
}

test_operatingModel_get_target_value_hat2 <- function(flfs, biols, ctrl, target_no) {
    .Call(`_FLasherTests_test_operatingModel_get_target_value_hat2`, flfs, biols, ctrl, target_no)
}

test_operatingModel_get_target_value <- function(flfs, biols, ctrl, target_no, sim_target_no) {
    .Call(`_FLasherTests_test_operatingModel_get_target_value`, flfs, biols, ctrl, target_no, sim_target_no)
}

test_operatingModel_get_target_value2 <- function(flfs, biols, ctrl, target_no) {
    .Call(`_FLasherTests_test_operatingModel_get_target_value2`, flfs, biols, ctrl, target_no)
}

test_operatingModel_get_target_hat_indices <- function(flfs, biols, ctrl, target_no, sim_target_no, target_component, relative) {
    .Call(`_FLasherTests_test_operatingModel_get_target_hat_indices`, flfs, biols, ctrl, target_no, sim_target_no, target_component, relative)
}

test_operatingModel_catches_subset <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_catches_subset`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_landings_subset <- function(flfs, flbs_list_sexp, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_landings_subset`, flfs, flbs_list_sexp, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_discards_subset <- function(flfs, flbs_list_sexp, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_discards_subset`, flfs, flbs_list_sexp, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_catch_n_subset <- function(flfs, flbs_list_sexp, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_catch_n_subset`, flfs, flbs_list_sexp, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_landings_n_subset <- function(flfs, flbs_list_sexp, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_landings_n_subset`, flfs, flbs_list_sexp, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_discards_n_subset <- function(flfs, flbs_list_sexp, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_discards_n_subset`, flfs, flbs_list_sexp, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_ssb_start <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_ssb_start`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_biomass_start <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_biomass_start`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_ssb_end <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_ssb_end`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_ssb_spawn <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_ssb_spawn`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_ssb_flash <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_ssb_flash`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_biomass_flash <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_biomass_flash`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_biomass_end <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_biomass_end`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_biomass_spawn <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_biomass_spawn`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_spawn_before_fishing <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_spawn_before_fishing`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_operatingModel_fishing_before_spawn <- function(flfs, biols, ctrl, biol_no, indices_min, indices_max) {
    .Call(`_FLasherTests_test_operatingModel_fishing_before_spawn`, flfs, biols, ctrl, biol_no, indices_min, indices_max)
}

test_max3 <- function(indep) {
    .Call(`_FLasherTests_test_max3`, indep)
}

test_max2 <- function(indep) {
    .Call(`_FLasherTests_test_max2`, indep)
}

test_max <- function(indep) {
    .Call(`_FLasherTests_test_max`, indep)
}

test_standard_conditional <- function(indep) {
    .Call(`_FLasherTests_test_standard_conditional`, indep)
}

test_cppad_conditional <- function(indep) {
    .Call(`_FLasherTests_test_cppad_conditional`, indep)
}

test_euclid_norm <- function(xvec) {
    .Call(`_FLasherTests_test_euclid_norm`, xvec)
}

test_NR_quad_iters <- function(coefs, initial_value, max_iters, indep_min, indep_max, tolerance) {
    .Call(`_FLasherTests_test_NR_quad_iters`, coefs, initial_value, max_iters, indep_min, indep_max, tolerance)
}

test_NR_linear <- function(initial_value, coefs, max_iters, indep_min, indep_max, tolerance) {
    .Call(`_FLasherTests_test_NR_linear`, initial_value, coefs, max_iters, indep_min, indep_max, tolerance)
}

eval_user_function <- function(xpsexp, params) {
    .Call(`_FLasherTests_eval_user_function`, xpsexp, params)
}

eval_user_gradient <- function(xpsexp, params) {
    .Call(`_FLasherTests_eval_user_gradient`, xpsexp, params)
}

